name: practice

services:
    suitecrm:
        build: ./
        image: practice_suitecrm:latest
        networks:
            - suitecrm_net
        volumes:
            #SuiteCRM Application Folder
            - ./www/SuiteCRM:/var/www/suitecrm
            #SuiteCRM Log Folder
            - ./logs/SuiteCRM:/var/www/suitecrm/logs
            #PHP config
            - ./docker/config/php/php.ini:/etc/php/8.1/apache2/php.ini
            #APACHE Log Folder
            - ./logs/apache:/var/log/apache2/
            #PHP Log Folder
            - ./logs/php:/var/log/php/
        environment:
            - DATABASE_USERNAME=suitecrm
            - DATABASE_PASSWORD=password
            - DATABASE_SERVER=mysql
            - DATABASE_NAME=suitecrm
            - SITE_HOST="http://localhost/"
            - DATABASE_PORT=3306
            - DATABASE_URL=mysql://suitecrm:password@mysql:3306/suitecrm
            # - environment/sample.env
            #- environment/.env
        ports:
            - "80:80"

    mysql:
        image: mariadb:10.6
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=suitecrm
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=password
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        networks:
            - suitecrm_net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        ports:
            - 8181:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=admin
            - PMA_PASSWORD=password
        networks:
            - suitecrm_net
networks:
    suitecrm_net:
        driver: bridge
